<a href="https://colab.research.google.com/github/ALiMehran01/20SW008/blob/main/Lab4_20sw008.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

LAB NO 4
Section 2
Roll NO 20sw008

Task No 1

In [1]:
import numpy as np

#using the range function to generate the even numbers
e_num = np.arange(2, 34, 2)

X = e_num.reshape(4, 4)

print(X)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]


Task No 2

In [2]:
import numpy as np

# Create a 5 x 5 ndarray with consecutive integers from 1 to 25
X = np.arange(1, 26).reshape(5, 5)

# Use Boolean indexing to pick out only the odd numbers
Y = X[X % 2 != 0]

#printing the origenal array
print("Original array X:\n", X)

#printing the odd numbers
print("\nArray Y with odd numbers:\n", Y)

Original array X:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Array Y with odd numbers:
 [ 1  3  5  7  9 11 13 15 17 19 21 23 25]


Task No 3

In [3]:
import numpy as np

# Creating a 4 x 4 ndarray with columns of consecutive numbers
X = np.arange(1, 5)

# Using broadcasting to create the desired array
X = X[:, np.newaxis] * np.ones((1, 4), dtype=int)

#printing the array
print(X)

[[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]]


Task No 4

In [4]:
import numpy as np

# Create a random permutation of integers 0 to 4
permuted_indices = np.random.permutation(5)

# Create a 1000 x 20 ndarray with random integers in the half-open interval [0, 5001).
X = np.random.randint(0, 5001, size=(1000, 20))

# Create a rank 1 ndarray that contains a random permutation of the row indices of `X`
row_indices = np.random.permutation(X.shape[0])

# Make any necessary calculations.
# You can save your calculations into variables to use later.

# Create a Training Set
X_train = X[row_indices[:700], :]

# Create a Cross Validation Set
X_crossVal = X[row_indices[700:850], :]

# Create a Test Set
X_test = X[row_indices[850:], :]

# Print the shape of X_train
print("Shape of X_train:", X_train.shape)

# Print the shape of X_crossVal
print("Shape of X_crossVal:", X_crossVal.shape)

# Print the shape of X_test
print("Shape of X_test:", X_test.shape)

Shape of X_train: (700, 20)
Shape of X_crossVal: (150, 20)
Shape of X_test: (150, 20)
